### ISSUE TITLE
torch in requirements.txt breaks forge neo due to a torch update (torch 2.9.0)

### ISSUE THREAD

**Issue by 6Morpheus6** [Haoming02/sd-webui-forge-classic#269]
Forge neo refuses to start with `AssertionError: Torch not compiled with CUDA enabled`

```
Creating venv in directory C:\pinokio\api\forge-neo.git\app\venv using python "C:\pinokio\bin\miniconda\python.exe"
Requirement already satisfied: pip in c:\pinokio\api\forge-neo.git\app\venv\lib\site-packages (23.0.1)
Collecting pip
  Downloading pip-25.2-py3-none-any.whl (1.8 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.8/1.8 MB 13.9 MB/s eta 0:00:00
Installing collected packages: pip
  Attempting uninstall: pip
    Found existing installation: pip 23.0.1
    Uninstalling pip-23.0.1:
      Successfully uninstalled pip-23.0.1
Successfully installed pip-25.2
venv "C:\pinokio\api\forge-neo.git\app\venv\Scripts\Python.exe"
===========================================================================================
This program is tested with 3.11.9 Python, but you have 3.10.16.
            If you encounter any error regarding unsuccessful package/library installation,
            please downgrade (or upgrade) to the latest version of 3.11 Python,
            and delete the current Python "venv" folder in WebUI's directory.
            Use --skip-python-version-check to suppress this warning
===========================================================================================
Python 3.10.16 | packaged by Anaconda, Inc. | (main, Dec 11 2024, 16:19:12) [MSC v.1929 64 bit (AMD64)]
Version: neo
Installing torch and torchvision
Using Python 3.10.16 environment at: venv
Resolved 12 packages in 594ms
Prepared 6 packages in 816ms
Installed 12 packages in 1.22s
 + filelock==3.19.1                                                                                                                                                                                                                   
 + fsspec==2025.9.0                                                                                                                                                                                                                   
 + jinja2==3.1.6                                                                                                                                                                                                                      
 + markupsafe==2.1.5
 + mpmath==1.3.0
 + networkx==3.3
 + numpy==2.1.2
 + pillow==11.3.0
 + sympy==1.14.0
 + torch==2.8.0+cu128
 + torchvision==0.23.0+cu128
 + typing-extensions==4.15.0
Installing packaging
Installing clip
Installing nunchaku
Installing gradio
Installing requirements
Installing forge_legacy_preprocessor requirement: fvcore
Installing forge_legacy_preprocessor requirement: mediapipe
Installing forge_legacy_preprocessor requirement: onnxruntime
Installing forge_legacy_preprocessor requirement: svglib
Installing forge_legacy_preprocessor requirement: insightface
Installing forge_legacy_preprocessor requirement: handrefinerportable
Installing forge_legacy_preprocessor requirement: depth_anything
Installing forge_legacy_preprocessor requirement: depth_anything_v2
Installing requirements
Launching Web UI with arguments: --uv
Traceback (most recent call last):
  File "C:\pinokio\api\forge-neo.git\app\launch.py", line 52, in <module>
    main()
  File "C:\pinokio\api\forge-neo.git\app\launch.py", line 48, in main
    start()
  File "C:\pinokio\api\forge-neo.git\app\modules\launch_utils.py", line 473, in start
    import webui
  File "C:\pinokio\api\forge-neo.git\app\webui.py", line 23, in <module>
    initialize_forge()
  File "C:\pinokio\api\forge-neo.git\app\modules_forge\initialization.py", line 67, in initialize_forge
    from backend import memory_management
  File "C:\pinokio\api\forge-neo.git\app\backend\memory_management.py", line 132, in <module>
    total_vram = get_total_memory(get_torch_device()) / (1024 * 1024)
  File "C:\pinokio\api\forge-neo.git\app\backend\memory_management.py", line 99, in get_torch_device
    return torch.device(torch.cuda.current_device())
  File "C:\pinokio\api\forge-neo.git\app\venv\lib\site-packages\torch\cuda\__init__.py", line 1069, in current_device
    _lazy_init()
  File "C:\pinokio\api\forge-neo.git\app\venv\lib\site-packages\torch\cuda\__init__.py", line 403, in _lazy_init
    raise AssertionError("Torch not compiled with CUDA enabled")
AssertionError: Torch not compiled with CUDA enabled
Press any key to continue . . . 
```

This happens although torch+cu128 was installed in a previous step.
The reason is that torch is listed at the bottom of requirements.txt
The latest stable torch version is now torch 2.9.0 which results in an uninstallation of torch 2.8.0+cu128 and an installation of torch 2.9.0+cpu
If you don't mind, please remove torch from requirements.txt or pin the version to torch 2.8.0
Related but closed issue https://github.com/Haoming02/sd-webui-forge-classic/issues/267

After some testing it turns out removing torch wouldn't be enough since bitsandbytes also pulls the latest torch version.
A possible fix could be to install torch after the requirements.

**Comment by Haoming02** [comment]
Hello, can you try again to see if the Issue has been fixed?

**Comment by 6Morpheus6** [comment]
@Haoming02 Thanks for the quick reply. :)
Sadly the error is still present.

<img width="2214" height="1810" alt="Image" src="https://github.com/user-attachments/assets/8f6aa4fd-00aa-4c50-934e-7d57dfecc69a" />

Packages in this environment at this time:
```
(venv) (base) PS G:\pinokio\api\forge-neo-fixed.git\app> pip list
Package                   Version
------------------------- ------------------
absl-py                   2.3.1
accelerate                1.10.1
aiofiles                  23.2.1
aiohappyeyeballs          2.6.1
aiohttp                   3.13.0
aiosignal                 1.4.0
albucore                  0.0.24
albumentations            2.0.8
annotated-types           0.7.0
antlr4-python3-runtime    4.9.3
anyio                     3.7.1
async-timeout             5.0.1
attrs                     25.4.0
bitsandbytes              0.48.1
certifi                   2025.10.5
cffi                      2.0.0
charset-normalizer        3.4.4
clean-fid                 0.1.35
click                     8.3.0
clip                      1.0
colorama                  0.4.6
coloredlogs               15.0.1
colorlog                  6.9.0
contourpy                 1.3.2
cssselect2                0.8.0
cycler                    0.12.1
Cython                    3.1.4
depth_anything            2024.1.22.0
depth_anything_v2         2024.7.1.0
diffusers                 0.35.1
diskcache                 5.6.3
easydict                  1.13
einops                    0.8.1
exceptiongroup            1.3.0
facexlib                  0.3.0
fastapi                   0.112.4
ffmpy                     0.6.3
filelock                  3.20.0
filterpy                  1.4.5
flatbuffers               25.9.23
fonttools                 4.60.1
freetype-py               2.5.1
frozenlist                1.8.0
fsspec                    2025.9.0
ftfy                      6.3.1
fvcore                    0.1.5.post20221221
gitdb                     4.0.12
GitPython                 3.1.44
gradio                    4.40.0
gradio_client             1.2.0
gradio_imageslider        0.0.20
gradio_rangeslider        0.0.6
h11                       0.12.0
handrefinerportable       2024.2.12.0
httpcore                  0.15.0
httpx                     0.24.1
huggingface-hub           0.34.1
humanfriendly             10.0
idna                      3.11
imageio                   2.37.0
importlib_metadata        8.7.0
importlib_resources       6.5.2
inflection                0.5.1
insightface               0.7.3
iopath                    0.1.10
jax                       0.6.2
jaxlib                    0.6.2
Jinja2                    3.1.6
joblib                    1.5.1
jsonmerge                 1.8.0
jsonschema                4.25.1
jsonschema-specifications 2025.9.1
kiwisolver                1.4.9
kornia                    0.6.7
lark                      1.2.2
lazy_loader               0.4
lightning                 2.5.1
lightning-utilities       0.15.2
llvmlite                  0.45.1
loadimg                   0.1.2
lxml                      6.0.2
manifold3d                3.2.1
mapbox_earcut             1.0.3
markdown-it-py            4.0.0
MarkupSafe                3.0.3
matplotlib                3.10.7
mdurl                     0.1.2
mediapipe                 0.10.21
ml_dtypes                 0.5.3
mpmath                    1.3.0
multidict                 6.7.0
networkx                  3.4.2
numba                     0.62.1
numpy                     1.26.4
nunchaku                  1.0.1+torch2.8
omegaconf                 2.2.3
onnx                      1.19.1
onnxruntime               1.23.1
open_clip_torch           2.32.0
opencv-contrib-python     4.11.0.86
opencv-python             4.8.1.78
opencv-python-headless    4.11.0.86
opt_einsum                3.4.0
orjson                    3.11.3
packaging                 24.2
pandas                    2.3.3
peft                      0.17.1
piexif                    1.1.3
pillow                    11.3.0
pillow_heif               0.22.0
pip                       25.2
portalocker               3.2.0
prettytable               3.16.0
propcache                 0.4.1
protobuf                  4.25.7
psutil                    5.9.8
pycairo                   1.28.0
pycollada                 0.9.2
pycparser                 2.23
pydantic                  2.9.2
pydantic_core             2.23.4
pydub                     0.25.1
Pygments                  2.19.2
pyparsing                 3.2.5
pyreadline3               3.5.4
python-dateutil           2.9.0.post0
python-multipart          0.0.20
pytorch-lightning         2.5.5
pytz                      2025.2
pywin32                   311
PyYAML                    6.0.3
referencing               0.37.0
regex                     2025.9.18
reportlab                 4.4.4
requests                  2.32.5
resize-right              0.0.2
rich                      14.2.0
rlPyCairo                 0.4.0
rpds-py                   0.27.1
rtree                     1.4.1
ruff                      0.14.0
safetensors               0.6.2
scikit-image              0.25.2
scikit-learn              1.7.2
scipy                     1.15.3
semantic-version          2.10.0
sentencepiece             0.2.1
setuptools                69.5.1
shapely                   2.1.2
shellingham               1.5.4
simsimd                   6.5.3
six                       1.17.0
smmap                     5.0.2
sniffio                   1.3.1
sounddevice               0.5.2
spandrel                  0.4.1
spandrel_extra_arches     0.2.0
starlette                 0.38.6
stringzilla               4.2.1
svg.path                  7.0
svglib                    1.6.0
sympy                     1.14.0
tabulate                  0.9.0
termcolor                 3.1.0
threadpoolctl             3.6.0
tifffile                  2025.5.10
timm                      1.0.20
tinycss2                  1.4.0
tokenizers                0.22.1
tomesd                    0.1.3
tomlkit                   0.12.0
torch                     2.9.0
torchdiffeq               0.2.5
torchmetrics              1.8.2
torchsde                  0.2.6
torchvision               0.24.0
tqdm                      4.67.1
trampoline                0.1.2
transformers              4.56.2
trimesh                   4.8.3
typer                     0.19.2
typing_extensions         4.15.0
typing-inspection         0.4.2
tzdata                    2025.2
urllib3                   2.5.0
uvicorn                   0.37.0
vhacdx                    0.0.8.post2
wcwidth                   0.2.14
webencodings              0.5.1
websockets                12.0
xxhash                    3.6.0
yacs                      0.1.8
yarl                      1.22.0
zipp                      3.23.0
```

**Comment by Haoming02** [comment]
Can you try the latest commit again?

**Comment by saka7811** [comment]
Using the latest commit still not working same error

**Comment by 6Morpheus6** [comment]
@Haoming02 I can confirm. It still fails with the same error.
But something is new now.
torch 2.8.0+cu128 gets installed and during the installation of the requirements it gets replaced by torch 2.8.0+cpu now.

<img width="2130" height="1672" alt="Image" src="https://github.com/user-attachments/assets/328ca6d3-cf86-4f6c-8846-7cfac862ed48" />
___  

torch version in the venv after the error:
<img width="1976" height="516" alt="Image" src="https://github.com/user-attachments/assets/a413663e-129a-4ae1-8191-c7dacb4d64d1" />

**Comment by Haoming02** [comment]
bruh, what the heck is reinstalling `torch` 🫠

**Comment by Haoming02** [comment]
Hello, this should be fixed now~

~~At least it finally installed correctly for me~~

**Comment by ChuuniKaede** [comment]
> Hello, this should be fixed now~
> 
> ~At least it finally installed correctly for me~

confirming that it fixed my issue too.

**Comment by 6Morpheus6** [comment]
It works for me as well again.
Thanks a lot @Haoming02  :)

**Comment by sameshrimp** [comment]
I'm still getting this issue. Just did a fresh installation through Stability Matrix and keep getting torch replaced with the non CUDA version. Tried reinstalling with different commits, didn't work. Tried uninstalling torch then manually installing the right version, still changed back.

**Comment by Haoming02** [comment]
I'm 99% sure it's **StabilityMatrix** 's problem

See #277 for solution

**Comment by sameshrimp** [comment]
Ah, yep that worked. Thanks!
