### ISSUE TITLE
OOM errors when doing a hires fix using large upscalers

### ISSUE THREAD

**Issue by Speeskees** [Haoming02/sd-webui-forge-classic#622]
When doing a hires fix workflow, the diffusion model seems to remain in VRAM during the upscale phase, even if this results in exceeding the maximum amount of VRAM. When using a DCRT-L upscaler model with large (512x512) tiles (GPU tile composition off), I always get an OOM during the upscale phase on my RTX 3060 12GB. Keeping the diffusion model in VRAM during upscaling in a hires fix workflow is useful for speed, as the model likely be used again during the second denoising phase, but the new offloading mechanism does not seem to keep the upscaler memory usage into account. The `--always-offload-from-vram` option doesn't seem to work anymore. Is there a way to disable keeping the diffusion model in VRAM during upscaling, or could this be added? Currently, the only way I do not get OOM errors is to either use --novram or NeverOOM Unet, but this results in exclusively black outputs now.

I use the following commandline args:

```
set COMMANDLINE_ARGS= ^
  --uv ^
  --xformers ^
  --flash ^
  --bnb ^
  --nunchaku
```

**Comment by Haoming02** [comment]
Wait, so you do not get **OOM** if you use `Latent Upscale` instead of an Upscaler?

**Comment by Speeskees** [comment]
Did some more testing, and that is correct. Latent upscaling adds very little VRAM usage, and the second denoising phase progresses fine without any OOM errors. The same happens with Lanczos upscaling. I only get OOM errors with large models, combined with large upscalers / tiles. As both do not fit within my VRAM simultaneously, an OOM error is thrown when the upscaler is loaded. It would theoretically be possible to complete the workflow, if the diffusion model / latents / anything not related to upscaling were to be offloaded to RAM. The OOM errors also happen if I manually upscale in the extra's tab after generating an image, as the diffusion model is not removed from VRAM after a generation, when an upscale is started outside of the hires fix workflow, either. I've tested both FLUX.1 Dev SVDQ, which I've experienced to be a bit more sticky in VRAM, and FP16 SDXL, and the issue happens for both.

The black outputs turned out to be caused by my PC being haunted: RAM instability after adding a USB device with power issues. The OOM issues persist.

**Comment by Haoming02** [comment]
Wait, did the console not print `Cleanup minimal inference memory...` when upscaling?

**Comment by Haoming02** [comment]
I just tried generating a `2048x2048` image, then `Hires. fix` using `4x-UltraSharpV2` to `8192x8192` on a `RTX 3060`. It correctly offloads the model during upscale, and everything went fine.

**Comment by Speeskees** [comment]
I'll do some more testing when I get back to my PC, but my VPN crapped out, so I currently cannot access my setup.

I got OOM errors using 512x512 tiles with 64 overlap, CPU tile composition (GPU also blows up), and full-precision. I use these 2 upscalers:

https://huggingface.co/Phips/4xNomos2_hq_drct-l
https://openmodeldb.info/models/4x-Nomos2-hq-dat2

They work fine at 256x256 tiles with 64 overlap, but upscaling takes quite long that way. It does seem pretty weird how 256x256 tiles barely take up anything, and 512x512 tiles eat up more than half my VRAM, when the upscaler phase comes around.

I'll get back to you on the exact log output and non-tiled upscaling.

**Comment by Speeskees** [comment]
```
equested to load JointTextEncoder                                                                                                                                               memory_management.py :: INFO
loaded completely; 4419.44 MB usable, 2524.98 MB loaded, full load: True                                                                                                                      base.py :: INFO
Moving model(s) has taken 0.42 seconds                                                                                                                                           memory_management.py :: INFO
Moving model(s) has taken 0.00 seconds                                                                                                                                           memory_management.py :: INFO
Moving model(s) has taken 0.00 seconds                                                                                                                                           memory_management.py :: INFO
Moving model(s) has taken 0.00 seconds                                                                                                                                           memory_management.py :: INFO
eps_scaling_factor = 1.02
                                                                                                                                                                                                                Requested to load KModel                                                                                                                                                         memory_management.py :: INFO
Moving model(s) has taken 0.00 seconds                                                                                                                                           memory_management.py :: INFO
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 50/50 [00:27<00:00,  1.81it/s]
Unloaded partially: 854.14 MB freed, 705.53 MB remains loaded, 37.51 MB buffer reserved, lowvram patches: 0                                                                                   base.py :: INFO
Moving model(s) has taken 0.19 seconds                                                                                                                                           memory_management.py :: INFO
Cleanup minimal inference memory...
tiled upscale (CPU Composite):   0%|                                                                                                                                                      | 0/6 [00:00<?, ?it/s]
Traceback (most recent call last):████████████████████████████████████████████████████████████████                                                                             | 50/100 [00:31<00:27,  1.83it/s]
  File "C:\Users\jairp\Programs\SD WebUI Forge Neo\modules_forge\main_thread.py", line 30, in work
    self.result = self.func(*self.args, **self.kwargs)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jairp\Programs\SD WebUI Forge Neo\modules\txt2img.py", line 135, in txt2img_function
    processed = processing.process_images(p)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jairp\Programs\SD WebUI Forge Neo\modules\processing.py", line 835, in process_images
    res = process_images_inner(p)
          ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jairp\Programs\SD WebUI Forge Neo\modules\processing.py", line 990, in process_images_inner
    samples_ddim = p.sample(conditioning=p.c, unconditional_conditioning=p.uc, seeds=p.seeds, subseeds=p.subseeds, subseed_strength=p.subseed_strength, prompts=p.prompts)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jairp\Programs\SD WebUI Forge Neo\modules\processing.py", line 1441, in sample
    return self.sample_hr_pass(samples, decoded_samples, seeds, subseeds, subseed_strength, prompts)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jairp\Programs\SD WebUI Forge Neo\modules\processing.py", line 1490, in sample_hr_pass
    image = images.resize_image(0, image, target_width, target_height, upscaler_name=self.hr_upscaler)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jairp\Programs\SD WebUI Forge Neo\modules\images.py", line 298, in resize_image
    res = resize(im, width, height)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jairp\Programs\SD WebUI Forge Neo\modules\images.py", line 290, in resize
    im = upscaler.scaler.upscale(im, scale, upscaler.data_path)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jairp\Programs\SD WebUI Forge Neo\modules\upscaler.py", line 56, in upscale
    img = self.do_upscale(img, selected_model)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jairp\Programs\SD WebUI Forge Neo\modules\esrgan_model.py", line 55, in do_upscale
    return upscale_with_model(
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jairp\Programs\SD WebUI Forge Neo\modules\upscaler_utils.py", line 279, in upscale_with_model
    return upscale_with_model_cpu(model, img, tile_size=tile_size, tile_overlap=tile_overlap, desc=f"{desc} (CPU Composite)")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jairp\Programs\SD WebUI Forge Neo\modules\upscaler_utils.py", line 250, in upscale_with_model_cpu
    output = upscale_pil_patch(model, tile)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jairp\Programs\SD WebUI Forge Neo\modules\upscaler_utils.py", line 219, in upscale_pil_patch
    return torch_bgr_to_pil_image(_model(model, tensor))
                                  ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jairp\Programs\SD WebUI Forge Neo\modules\upscaler_utils.py", line 73, in _model
    return model(x)
           ^^^^^^^^
  File "C:\Users\jairp\Programs\SD WebUI Forge Neo\venv\Lib\site-packages\torch\utils\_contextlib.py", line 120, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jairp\Programs\SD WebUI Forge Neo\venv\Lib\site-packages\spandrel\__helpers\model_descriptor.py", line 472, in __call__
    output = self._call_fn(self.model, image)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jairp\Programs\SD WebUI Forge Neo\venv\Lib\site-packages\spandrel\__helpers\model_descriptor.py", line 439, in <lambda>
    self._call_fn = call_fn or (lambda model, image: model(image))
                                                     ^^^^^^^^^^^^
  File "C:\Users\jairp\Programs\SD WebUI Forge Neo\venv\Lib\site-packages\torch\nn\modules\module.py", line 1775, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jairp\Programs\SD WebUI Forge Neo\venv\Lib\site-packages\torch\nn\modules\module.py", line 1786, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jairp\Programs\SD WebUI Forge Neo\venv\Lib\site-packages\spandrel\architectures\DRCT\__arch\drct_arch.py", line 857, in forward
    x = self.conv_after_body(self.forward_features(x)) + x
                             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jairp\Programs\SD WebUI Forge Neo\venv\Lib\site-packages\spandrel\architectures\DRCT\__arch\drct_arch.py", line 843, in forward_features
    x = layer(x, x_size)
        ^^^^^^^^^^^^^^^^
  File "C:\Users\jairp\Programs\SD WebUI Forge Neo\venv\Lib\site-packages\torch\nn\modules\module.py", line 1775, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jairp\Programs\SD WebUI Forge Neo\venv\Lib\site-packages\torch\nn\modules\module.py", line 1786, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jairp\Programs\SD WebUI Forge Neo\venv\Lib\site-packages\spandrel\architectures\DRCT\__arch\drct_arch.py", line 343, in forward
    x1 = self.pe(self.lrelu(self.adjust1(self.pue(self.swin1(x, xsize), xsize))))
                                                  ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jairp\Programs\SD WebUI Forge Neo\venv\Lib\site-packages\torch\nn\modules\module.py", line 1775, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jairp\Programs\SD WebUI Forge Neo\venv\Lib\site-packages\torch\nn\modules\module.py", line 1786, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jairp\Programs\SD WebUI Forge Neo\venv\Lib\site-packages\spandrel\architectures\DRCT\__arch\drct_arch.py", line 511, in forward
    attn_windows = self.attn(
                   ^^^^^^^^^^
  File "C:\Users\jairp\Programs\SD WebUI Forge Neo\venv\Lib\site-packages\torch\nn\modules\module.py", line 1775, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jairp\Programs\SD WebUI Forge Neo\venv\Lib\site-packages\torch\nn\modules\module.py", line 1786, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jairp\Programs\SD WebUI Forge Neo\venv\Lib\site-packages\spandrel\architectures\DRCT\__arch\drct_arch.py", line 201, in forward
    attn = attn + relative_position_bias.unsqueeze(0)
           ~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
torch.OutOfMemoryError: Allocation on device
Allocation on device

Total progress:  50%|█████████████████████████████████████████████████████████████████████████████                                                                             | 50/100 [00:33<00:27,  1.83it/s]
```

It does seem to print "Cleanup minimal inference memory...", but I don't see the VRAM use going down in the task manager, and once it starts to upscale, the VRAM graph very quickly jump to near 100% and I get the OOM. Now that I've enabled xformers, it seems there's just enough VRAM to support a DAT2-based upscaler without OOM errors, but the DRCT-L upscaler still throws OOMs with 512x512 tiles.

**Comment by Speeskees** [comment]
<img width="1466" height="918" alt="Image" src="https://github.com/user-attachments/assets/5df280ea-5c69-43f5-a98e-48b439092162" />

Memory also remains reserved / stuck on the GPU after the OOM, causing this:

```
NeverOOM] Enabled for VAE (always tiled)                                                                                                                                          forge_never_oom.py :: INFO
eps_scaling_factor = 1.02
                                                                                                                                                                                                                Requested to load KModel                                                                                                                                                         memory_management.py :: INFO
Unloaded partially: 125.03 MB freed, 580.50 MB remains loaded, 37.51 MB buffer reserved, lowvram patches: 0                                                                                   base.py :: INFO
Moving model(s) has taken 0.07 seconds                                                                                                                                           memory_management.py :: INFO
  0%|                                                                                                                                                                                    | 0/50 [00:00<?, ?it/s]The current free memory for GPU is 1449.79 MB                                                                                                                                    sampling_function.py :: WARNING
This number is lower than the safe threshold ; This may cause extreme slow performance                                                                                           sampling_function.py :: WARNING
You can add "--reserve-vram 2" to keep a larger headroom                                                                                                                         sampling_function.py :: WARNING
You can also (not recommended) add "--disable-gpu-warning" to remove this warning                                                                                                sampling_function.py :: WARNING
  2%|███▍                                                                                                                                                                        | 1/50 [00:00<00:17,  2.73it/s]The current free memory for GPU is 1446.99 MB                                                                                                                                    sampling_function.py :: WARNING
This number is lower than the safe threshold ; This may cause extreme slow performance                                                                                           sampling_function.py :: WARNING
You can add "--reserve-vram 2" to keep a larger headroom                                                                                                                         sampling_function.py :: WARNING
You can also (not recommended) add "--disable-gpu-warning" to remove this warning                                                                                                sampling_function.py :: WARNING
  4%|██████▉                                                                                                                                                                     | 2/50 [00:01<00:32,  1.48it/s]The current free memory for GPU is 1513.43 MB                                                                                                                                    sampling_function.py :: WARNING
This number is lower than the safe threshold ; This may cause extreme slow performance                                                                                           sampling_function.py :: WARNING
You can add "--reserve-vram 2" to keep a larger headroom                                                                                                                         sampling_function.py :: WARNING
You can also (not recommended) add "--disable-gpu-warning" to remove this warning                                                                                                sampling_function.py :: WARNING
  6%|██████████▎                                                                                                                                                                 | 3/50 [00:01<00:30,  1.52it/s]The current free memory for GPU is 1525.99 MB                                                                                                                                    sampling_function.py :: WARNING
This number is lower than the safe threshold ; This may cause extreme slow performance                                                                                           sampling_function.py :: WARNING
You can add "--reserve-vram 2" to keep a larger headroom                                                                                                                         sampling_function.py :: WARNING
You can also (not recommended) add "--disable-gpu-warning" to remove this warning                                                                                                sampling_function.py :: WARNING
 16%|███████████████████████████▌                                                                                                                                                | 8/50 [00:04<00:24,  1.70it/s]The current free memory for GPU is 1515.68 MB                                                                                                                                    sampling_function.py :: WARNING
This number is lower than the safe threshold ; This may cause extreme slow performance                                                                                           sampling_function.py :: WARNING
You can add "--reserve-vram 2" to keep a larger headroom                                                                                                                         sampling_function.py :: WARNING
You can also (not recommended) add "--disable-gpu-warning" to remove this warning                                                                                                sampling_function.py :: WARNING
 42%|███████████████████████████████████████████████████████████████████████▊                                                                                                   | 21/50 [00:12<00:15,  1.82it/s]The current free memory for GPU is 1496.74 MB                                                                                                                                    sampling_function.py :: WARNING
This number is lower than the safe threshold ; This may cause extreme slow performance                                                                                           sampling_function.py :: WARNING
You can add "--reserve-vram 2" to keep a larger headroom                                                                                                                         sampling_function.py :: WARNING
You can also (not recommended) add "--disable-gpu-warning" to remove this warning                                                                                                sampling_function.py :: WARNING
 96%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏      | 48/50 [00:27<00:01,  1.80it/s]The current free memory for GPU is 1503.49 MB                                                                                                                                    sampling_function.py :: WARNING
This number is lower than the safe threshold ; This may cause extreme slow performance                                                                                           sampling_function.py :: WARNING
You can add "--reserve-vram 2" to keep a larger headroom                                                                                                                         sampling_function.py :: WARNING
You can also (not recommended) add "--disable-gpu-warning" to remove this warning                                                                                                sampling_function.py :: WARNING
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 50/50 [00:28<00:00,  1.78it/s]
Unloaded partially: 2595.00 MB freed, 2302.06 MB remains loaded, 37.51 MB buffer reserved, lowvram patches: 0                                                                                 base.py :: INFO
Moving model(s) has taken 0.65 seconds                                                                                                                                           memory_management.py :: INFO
Cleanup minimal inference memory...
tiled upscale (CPU Composite):  17%|███████████████████████▋                                                                                                                      | 1/6 [00:07<00:35,  7.07s/it]
Total progress: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 100/100 [02:02<00:00,  1.71it/s]
```

**Comment by Speeskees** [comment]
```
venv "C:\Users\jairp\Programs\SD WebUI Forge Neo\venv\Scripts\Python.exe"
Launching Web UI with arguments: --listen --port 80 --enable-insecure-extension-access --uv --xformers --flash --bnb --nunchaku --fast-fp16 --cuda-malloc --cuda-stream --skip-python-version-check --skip-torch-cuda-test --skip-version-check --skip-prepare-environment --skip-install
Total VRAM 12288 MB, total RAM 32684 MB                                                 memory_management.py :: INFO
PyTorch Version: 2.9.1+cu130                                                            memory_management.py :: INFO
allow_fp16_accumulation: True                                                           memory_management.py :: INFO
VRAM State: NORMAL_VRAM                                                                 memory_management.py :: INFO
Device: NVIDIA GeForce RTX 3060 (cuda:0) - cudaMallocAsync                              memory_management.py :: INFO
Using async weight offloading with 2 streams                                            memory_management.py :: INFO
Using FlashAttention                                                                            attention.py :: INFO
Using xformers Attention for VAE                                                                attention.py :: INFO
[-] ADetailer initialized. version: 25.3.0, num models: 10
Using sqlite file: C:\Users\jairp\Programs\SD WebUI Forge Neo\extensions\sd-webui-forge-neo-agent-scheduler\task_scheduler.sqlite3
Model Selected:                                                                                main_entry.py :: INFO
{
  "checkpoint": "[XL] WAI Illustrious V16.safetensors",
  "modules": [],
  "dtype": "[torch.float16, torch.bfloat16]"
}
Patch LoRAs on-the-fly: False                                                                  main_entry.py :: INFO
Running on local URL:  http://0.0.0.0:80

To create a public link, set `share=True` in `launch()`.
🤯 LobeTheme: Initializing...
Startup time: 27.3s (launcher: 0.9s, forge init: 9.8s, shared init: 0.2s, misc. imports: 4.7s, load scripts: 1.9s, create ui: 3.2s, gradio launch: 4.8s, app_started_callback: 1.7s).
Loading Model: {'checkpoint_info': {'filename': 'C:\\Users\\jairp\\Programs\\SD WebUI Forge Neo\\models\\Stable-diffusion\\[XL] WAI Illustrious V16.safetensors', 'hash': '4748a7f6'}, 'additional_modules': [], 'unet_storage_dtype': None}
Using Default Model Data Type: torch.float16                                                       loader.py :: INFO
K-Model Created: {'storage_dtype': torch.float16, 'computation_dtype': torch.float16}
Model loaded in 1.0s (unload existing model: 0.2s, forge model load: 0.8s).
[NeverOOM] Enabled for VAE (always tiled)                                                 forge_never_oom.py :: INFO
                                  Requested to load JointTextEncoder                                                      memory_management.py :: INFO
loaded completely; 9811.80 MB usable, 1945.68 MB loaded, full load: True                             base.py :: INFO
Moving model(s) has taken 0.71 seconds                                                  memory_management.py :: INFO
Moving model(s) has taken 0.00 seconds                                                  memory_management.py :: INFO
Moving model(s) has taken 0.00 seconds                                                  memory_management.py :: INFO
Moving model(s) has taken 0.00 seconds                                                  memory_management.py :: INFO
eps_scaling_factor = 1.02
                                                                                                                       Requested to load KModel                                                                memory_management.py :: INFO
loaded completely; 7790.26 MB usable, 4897.05 MB loaded, full load: True                                                                                                                      base.py :: INFO
Moving model(s) has taken 2.75 seconds                                                                                                                                           memory_management.py :: INFO
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 30/30 [01:29<00:00,  2.98s/it]
Requested to load IntegratedAutoencoderKL                                                                                                                                        memory_management.py :: INFO
loaded partially; 0.00 MB usable, 0.00 MB loaded, 159.56 MB offloaded, 13.50 MB buffer reserved, lowvram patches: 0                                                                           base.py :: INFO
Moving model(s) has taken 1.59 seconds                                                                                                                                           memory_management.py :: INFO
Cleanup minimal inference memory...
                                                                                                                       Traceback (most recent call last):
  File "C:\Users\jairp\Programs\SD WebUI Forge Neo\modules_forge\main_thread.py", line 30, in work:50<01:24,  2.81s/it]
    self.result = self.func(*self.args, **self.kwargs)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jairp\Programs\SD WebUI Forge Neo\modules\txt2img.py", line 135, in txt2img_function
    processed = processing.process_images(p)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jairp\Programs\SD WebUI Forge Neo\modules\processing.py", line 835, in process_images
    res = process_images_inner(p)
          ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jairp\Programs\SD WebUI Forge Neo\modules\processing.py", line 990, in process_images_inner
    samples_ddim = p.sample(conditioning=p.c, unconditional_conditioning=p.uc, seeds=p.seeds, subseeds=p.subseeds, subseed_strength=p.subseed_strength, prompts=p.prompts)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jairp\Programs\SD WebUI Forge Neo\modules\processing.py", line 1441, in sample
    return self.sample_hr_pass(samples, decoded_samples, seeds, subseeds, subseed_strength, prompts)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jairp\Programs\SD WebUI Forge Neo\modules\processing.py", line 1490, in sample_hr_pass
    image = images.resize_image(0, image, target_width, target_height, upscaler_name=self.hr_upscaler)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jairp\Programs\SD WebUI Forge Neo\modules\images.py", line 298, in resize_image
    res = resize(im, width, height)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jairp\Programs\SD WebUI Forge Neo\modules\images.py", line 290, in resize
    im = upscaler.scaler.upscale(im, scale, upscaler.data_path)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jairp\Programs\SD WebUI Forge Neo\modules\upscaler.py", line 56, in upscale
    img = self.do_upscale(img, selected_model)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jairp\Programs\SD WebUI Forge Neo\modules\esrgan_model.py", line 55, in do_upscale
    return upscale_with_model(
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jairp\Programs\SD WebUI Forge Neo\modules\upscaler_utils.py", line 279, in upscale_with_model
    return upscale_with_model_cpu(model, img, tile_size=tile_size, tile_overlap=tile_overlap, desc=f"{desc} (CPU Composite)")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jairp\Programs\SD WebUI Forge Neo\modules\upscaler_utils.py", line 232, in upscale_with_model_cpu
    output = upscale_pil_patch(model, img)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jairp\Programs\SD WebUI Forge Neo\modules\upscaler_utils.py", line 219, in upscale_pil_patch
    return torch_bgr_to_pil_image(_model(model, tensor))
                                  ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jairp\Programs\SD WebUI Forge Neo\modules\upscaler_utils.py", line 73, in _model
    return model(x)
           ^^^^^^^^
  File "C:\Users\jairp\Programs\SD WebUI Forge Neo\venv\Lib\site-packages\torch\utils\_contextlib.py", line 120, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jairp\Programs\SD WebUI Forge Neo\venv\Lib\site-packages\spandrel\__helpers\model_descriptor.py", line 472, in __call__
    output = self._call_fn(self.model, image)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jairp\Programs\SD WebUI Forge Neo\venv\Lib\site-packages\spandrel\__helpers\model_descriptor.py", line 439, in <lambda>
    self._call_fn = call_fn or (lambda model, image: model(image))
                                                     ^^^^^^^^^^^^
  File "C:\Users\jairp\Programs\SD WebUI Forge Neo\venv\Lib\site-packages\torch\nn\modules\module.py", line 1775, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jairp\Programs\SD WebUI Forge Neo\venv\Lib\site-packages\torch\nn\modules\module.py", line 1786, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jairp\Programs\SD WebUI Forge Neo\venv\Lib\site-packages\spandrel\architectures\DAT\__arch\DAT.py", line 1062, in forward
    x = self.conv_after_body(self.forward_features(x)) + x
                             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jairp\Programs\SD WebUI Forge Neo\venv\Lib\site-packages\spandrel\architectures\DAT\__arch\DAT.py", line 1046, in forward_features
    x = layer(x, x_size)
        ^^^^^^^^^^^^^^^^
  File "C:\Users\jairp\Programs\SD WebUI Forge Neo\venv\Lib\site-packages\torch\nn\modules\module.py", line 1775, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jairp\Programs\SD WebUI Forge Neo\venv\Lib\site-packages\torch\nn\modules\module.py", line 1786, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jairp\Programs\SD WebUI Forge Neo\venv\Lib\site-packages\spandrel\architectures\DAT\__arch\DAT.py", line 839, in forward
    x = blk(x, x_size)
        ^^^^^^^^^^^^^^
  File "C:\Users\jairp\Programs\SD WebUI Forge Neo\venv\Lib\site-packages\torch\nn\modules\module.py", line 1775, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jairp\Programs\SD WebUI Forge Neo\venv\Lib\site-packages\torch\nn\modules\module.py", line 1786, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jairp\Programs\SD WebUI Forge Neo\venv\Lib\site-packages\spandrel\architectures\DAT\__arch\DAT.py", line 745, in forward
    x = x + self.drop_path(self.attn(self.norm1(x), H, W))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jairp\Programs\SD WebUI Forge Neo\venv\Lib\site-packages\torch\nn\modules\module.py", line 1775, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jairp\Programs\SD WebUI Forge Neo\venv\Lib\site-packages\torch\nn\modules\module.py", line 1786, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jairp\Programs\SD WebUI Forge Neo\venv\Lib\site-packages\spandrel\architectures\DAT\__arch\DAT.py", line 479, in forward
    qkv = self.qkv(x).reshape(B, -1, 3, C).permute(2, 0, 1, 3)  # 3, B, HW, C
          ^^^^^^^^^^^
  File "C:\Users\jairp\Programs\SD WebUI Forge Neo\venv\Lib\site-packages\torch\nn\modules\module.py", line 1775, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jairp\Programs\SD WebUI Forge Neo\venv\Lib\site-packages\torch\nn\modules\module.py", line 1786, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jairp\Programs\SD WebUI Forge Neo\venv\Lib\site-packages\torch\nn\modules\linear.py", line 134, in forward
    return F.linear(input, self.weight, self.bias)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
torch.OutOfMemoryError: Allocation on device
Allocation on device

Total progress:  50%|█████████████████████████████████                                 | 30/60 [01:51<01:24,  2.81s/it]

```

Doing a 2048x2048 to 8192x8192 upscale with the DAT2 model, without tiled upscaling, results in the same OOM issues. The DRCT-L model throws the same error, which makes sense, as that architecture consumes more VRAM than DAT2.

**Comment by Haoming02** [comment]
In the meantime, can you try adding `--reserve-vram 2` to see if `Hires. fix` with Upscaler works?

**Comment by Speeskees** [comment]
With `--reserve-vram 2` and upscaling from 2048x2048 to 8192x8192 (no tiling), the OOM still happens:

```
venv "C:\Users\jairp\Programs\SD WebUI Forge Neo\venv\Scripts\Python.exe"
Launching Web UI with arguments: --listen --port 80 --enable-insecure-extension-access --uv --xformers --flash --bnb --nunchaku --fast-fp16 --cuda-malloc --cuda-stream --reserve-vram 2 --skip-python-version-check --skip-torch-cuda-test --skip-version-check --skip-prepare-environment --skip-install
Total VRAM 12288 MB, total RAM 32684 MB                                                 memory_management.py :: INFO
PyTorch Version: 2.9.1+cu130                                                            memory_management.py :: INFO
allow_fp16_accumulation: True                                                           memory_management.py :: INFO
VRAM State: NORMAL_VRAM                                                                 memory_management.py :: INFO
Device: NVIDIA GeForce RTX 3060 (cuda:0) - cudaMallocAsync                              memory_management.py :: INFO
Reserving 2048 MB VRAM                                                                  memory_management.py :: INFO
Using async weight offloading with 2 streams                                            memory_management.py :: INFO
Using FlashAttention                                                                            attention.py :: INFO
Using xformers Attention for VAE                                                                attention.py :: INFO
[-] ADetailer initialized. version: 25.3.0, num models: 10
Using sqlite file: C:\Users\jairp\Programs\SD WebUI Forge Neo\extensions\sd-webui-forge-neo-agent-scheduler\task_scheduler.sqlite3
Model Selected:                                                                                main_entry.py :: INFO
{
  "checkpoint": "[XL] WAI Illustrious V16.safetensors",
  "modules": [],
  "dtype": "[torch.float16, torch.bfloat16]"
}
Patch LoRAs on-the-fly: False                                                                  main_entry.py :: INFO
Running on local URL:  http://0.0.0.0:80

To create a public link, set `share=True` in `launch()`.
🤯 LobeTheme: Initializing...
Startup time: 30.4s (launcher: 1.0s, forge init: 11.8s, shared init: 0.2s, misc. imports: 5.3s, list SD models: 0.1s, load scripts: 2.0s, create ui: 3.4s, gradio launch: 4.8s, app_started_callback: 1.8s).
Loading Model: {'checkpoint_info': {'filename': 'C:\\Users\\jairp\\Programs\\SD WebUI Forge Neo\\models\\Stable-diffusion\\[XL] WAI Illustrious V16.safetensors', 'hash': '4748a7f6'}, 'additional_modules': [], 'unet_storage_dtype': None}
Using Default Model Data Type: torch.float16                                                                                                                                                loader.py :: INFO
K-Model Created: {'storage_dtype': torch.float16, 'computation_dtype': torch.float16}
Model loaded in 1.8s (unload existing model: 0.2s, forge model load: 1.6s).
[NeverOOM] Enabled for VAE (always tiled)                                                                                                                                          forge_never_oom.py :: INFO
                                  Requested to load JointTextEncoder                                                                                                                                               memory_management.py :: INFO
loaded completely; 8363.80 MB usable, 1945.68 MB loaded, full load: True                                                                                                                      base.py :: INFO
Moving model(s) has taken 1.77 seconds                                                                                                                                           memory_management.py :: INFO
Moving model(s) has taken 0.00 seconds                                                                                                                                           memory_management.py :: INFO
Moving model(s) has taken 0.00 seconds                                                                                                                                           memory_management.py :: INFO
Moving model(s) has taken 0.00 seconds                                                                                                                                           memory_management.py :: INFO
eps_scaling_factor = 1.02
                                                                                                                                                                                                                Requested to load KModel                                                                                                                                                         memory_management.py :: INFO
Unloaded partially: 105.10 MB freed, 1454.58 MB remains loaded, 9.38 MB buffer reserved, lowvram patches: 0                                                                                   base.py :: INFO
loaded completely; 6447.36 MB usable, 4897.05 MB loaded, full load: True                                                                                                                      base.py :: INFO
Moving model(s) has taken 6.16 seconds                                                                                                                                           memory_management.py :: INFO
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 50/50 [02:16<00:00,  2.74s/it]
Requested to load IntegratedAutoencoderKL                                                                                                                                        memory_management.py :: INFO
loaded partially; 0.00 MB usable, 0.00 MB loaded, 159.56 MB offloaded, 13.50 MB buffer reserved, lowvram patches: 0                                                                           base.py :: INFO
Moving model(s) has taken 1.35 seconds                                                                                                                                           memory_management.py :: INFO
Cleanup minimal inference memory...
                                                                                                                                                                                                                Traceback (most recent call last):█████████████████████████████████████████████████████████████████                                                                             | 50/100 [02:42<02:16,  2.74s/it]
  File "C:\Users\jairp\Programs\SD WebUI Forge Neo\modules_forge\main_thread.py", line 30, in work
    self.result = self.func(*self.args, **self.kwargs)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jairp\Programs\SD WebUI Forge Neo\modules\txt2img.py", line 135, in txt2img_function
    processed = processing.process_images(p)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jairp\Programs\SD WebUI Forge Neo\modules\processing.py", line 835, in process_images
    res = process_images_inner(p)
          ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jairp\Programs\SD WebUI Forge Neo\modules\processing.py", line 990, in process_images_inner
    samples_ddim = p.sample(conditioning=p.c, unconditional_conditioning=p.uc, seeds=p.seeds, subseeds=p.subseeds, subseed_strength=p.subseed_strength, prompts=p.prompts)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jairp\Programs\SD WebUI Forge Neo\modules\processing.py", line 1441, in sample
    return self.sample_hr_pass(samples, decoded_samples, seeds, subseeds, subseed_strength, prompts)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jairp\Programs\SD WebUI Forge Neo\modules\processing.py", line 1490, in sample_hr_pass
    image = images.resize_image(0, image, target_width, target_height, upscaler_name=self.hr_upscaler)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jairp\Programs\SD WebUI Forge Neo\modules\images.py", line 298, in resize_image
    res = resize(im, width, height)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jairp\Programs\SD WebUI Forge Neo\modules\images.py", line 290, in resize
    im = upscaler.scaler.upscale(im, scale, upscaler.data_path)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jairp\Programs\SD WebUI Forge Neo\modules\upscaler.py", line 56, in upscale
    img = self.do_upscale(img, selected_model)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jairp\Programs\SD WebUI Forge Neo\modules\esrgan_model.py", line 55, in do_upscale
    return upscale_with_model(
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jairp\Programs\SD WebUI Forge Neo\modules\upscaler_utils.py", line 279, in upscale_with_model
    return upscale_with_model_cpu(model, img, tile_size=tile_size, tile_overlap=tile_overlap, desc=f"{desc} (CPU Composite)")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jairp\Programs\SD WebUI Forge Neo\modules\upscaler_utils.py", line 232, in upscale_with_model_cpu
    output = upscale_pil_patch(model, img)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jairp\Programs\SD WebUI Forge Neo\modules\upscaler_utils.py", line 219, in upscale_pil_patch
    return torch_bgr_to_pil_image(_model(model, tensor))
                                  ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jairp\Programs\SD WebUI Forge Neo\modules\upscaler_utils.py", line 73, in _model
    return model(x)
           ^^^^^^^^
  File "C:\Users\jairp\Programs\SD WebUI Forge Neo\venv\Lib\site-packages\torch\utils\_contextlib.py", line 120, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jairp\Programs\SD WebUI Forge Neo\venv\Lib\site-packages\spandrel\__helpers\model_descriptor.py", line 472, in __call__
    output = self._call_fn(self.model, image)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jairp\Programs\SD WebUI Forge Neo\venv\Lib\site-packages\spandrel\__helpers\model_descriptor.py", line 439, in <lambda>
    self._call_fn = call_fn or (lambda model, image: model(image))
                                                     ^^^^^^^^^^^^
  File "C:\Users\jairp\Programs\SD WebUI Forge Neo\venv\Lib\site-packages\torch\nn\modules\module.py", line 1775, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jairp\Programs\SD WebUI Forge Neo\venv\Lib\site-packages\torch\nn\modules\module.py", line 1786, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jairp\Programs\SD WebUI Forge Neo\venv\Lib\site-packages\spandrel\architectures\DRCT\__arch\drct_arch.py", line 857, in forward
    x = self.conv_after_body(self.forward_features(x)) + x
                             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jairp\Programs\SD WebUI Forge Neo\venv\Lib\site-packages\spandrel\architectures\DRCT\__arch\drct_arch.py", line 843, in forward_features
    x = layer(x, x_size)
        ^^^^^^^^^^^^^^^^
  File "C:\Users\jairp\Programs\SD WebUI Forge Neo\venv\Lib\site-packages\torch\nn\modules\module.py", line 1775, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jairp\Programs\SD WebUI Forge Neo\venv\Lib\site-packages\torch\nn\modules\module.py", line 1786, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jairp\Programs\SD WebUI Forge Neo\venv\Lib\site-packages\spandrel\architectures\DRCT\__arch\drct_arch.py", line 343, in forward
    x1 = self.pe(self.lrelu(self.adjust1(self.pue(self.swin1(x, xsize), xsize))))
                                                  ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jairp\Programs\SD WebUI Forge Neo\venv\Lib\site-packages\torch\nn\modules\module.py", line 1775, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jairp\Programs\SD WebUI Forge Neo\venv\Lib\site-packages\torch\nn\modules\module.py", line 1786, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jairp\Programs\SD WebUI Forge Neo\venv\Lib\site-packages\spandrel\architectures\DRCT\__arch\drct_arch.py", line 498, in forward
    x_windows = window_partition(
                ^^^^^^^^^^^^^^^^^
  File "C:\Users\jairp\Programs\SD WebUI Forge Neo\venv\Lib\site-packages\spandrel\architectures\DRCT\__arch\drct_arch.py", line 84, in window_partition
    x.permute(0, 1, 3, 2, 4, 5).contiguous().view(-1, window_size, window_size, C)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
torch.OutOfMemoryError: Allocation on device
Allocation on device

Total progress:  50%|█████████████████████████████████████████████████████████████████████████████                                                                             | 50/100 [02:43<02:16,  2.74s/it]
```

**Comment by Speeskees** [comment]
Same things when doing my usual upscale workflow (512x512 tiles, 1.5x upscaling from 1MP):

```
venv "C:\Users\jairp\Programs\SD WebUI Forge Neo\venv\Scripts\Python.exe"
Launching Web UI with arguments: --listen --port 80 --enable-insecure-extension-access --gradio-auth Speeskees:DikkemBaap420 --uv --xformers --flash --bnb --nunchaku --fast-fp16 --cuda-malloc --cuda-stream --reserve-vram 2 --skip-python-version-check --skip-torch-cuda-test --skip-version-check --skip-prepare-environment --skip-install
Total VRAM 12288 MB, total RAM 32684 MB                                                 memory_management.py :: INFO
PyTorch Version: 2.9.1+cu130                                                            memory_management.py :: INFO
allow_fp16_accumulation: True                                                           memory_management.py :: INFO
VRAM State: NORMAL_VRAM                                                                 memory_management.py :: INFO
Device: NVIDIA GeForce RTX 3060 (cuda:0) - cudaMallocAsync                              memory_management.py :: INFO
Reserving 2048 MB VRAM                                                                  memory_management.py :: INFO
Using async weight offloading with 2 streams                                            memory_management.py :: INFO
Using FlashAttention                                                                            attention.py :: INFO
Using xformers Attention for VAE                                                                attention.py :: INFO
[-] ADetailer initialized. version: 25.3.0, num models: 10
Using sqlite file: C:\Users\jairp\Programs\SD WebUI Forge Neo\extensions\sd-webui-forge-neo-agent-scheduler\task_scheduler.sqlite3
Model Selected:                                                                                main_entry.py :: INFO
{
  "checkpoint": "[XL] WAI Illustrious V16.safetensors",
  "modules": [],
  "dtype": "[torch.float16, torch.bfloat16]"
}
Patch LoRAs on-the-fly: False                                                                  main_entry.py :: INFO
Running on local URL:  http://0.0.0.0:80

To create a public link, set `share=True` in `launch()`.
🤯 LobeTheme: Initializing...
Startup time: 24.5s (launcher: 0.4s, forge init: 8.9s, shared init: 0.2s, misc. imports: 3.8s, load scripts: 1.8s, create ui: 2.9s, gradio launch: 4.8s, app_started_callback: 1.7s).
Loading Model: {'checkpoint_info': {'filename': 'C:\\Users\\jairp\\Programs\\SD WebUI Forge Neo\\models\\Stable-diffusion\\[XL] WAI Illustrious V16.safetensors', 'hash': '4748a7f6'}, 'additional_modules': [], 'unet_storage_dtype': None}
Using Default Model Data Type: torch.float16                                                       loader.py :: INFO
K-Model Created: {'storage_dtype': torch.float16, 'computation_dtype': torch.float16}
Model loaded in 0.8s (unload existing model: 0.2s, forge model load: 0.7s).
[NeverOOM] Enabled for VAE (always tiled)                                                 forge_never_oom.py :: INFO
                                  Requested to load JointTextEncoder                                                      memory_management.py :: INFO
loaded completely; 8363.80 MB usable, 1945.68 MB loaded, full load: True                             base.py :: INFO
Moving model(s) has taken 0.64 seconds                                                  memory_management.py :: INFO
Moving model(s) has taken 0.00 seconds                                                  memory_management.py :: INFO
Moving model(s) has taken 0.00 seconds                                                  memory_management.py :: INFO
Moving model(s) has taken 0.00 seconds                                                  memory_management.py :: INFO
eps_scaling_factor = 1.02
                                                                                                                       Requested to load KModel                                                                memory_management.py :: INFO
loaded completely; 6572.39 MB usable, 4897.05 MB loaded, full load: True                             base.py :: INFO
Moving model(s) has taken 2.64 seconds                                                  memory_management.py :: INFO
100%|██████████████████████████████████████████████████████████████████████████████████| 50/50 [00:29<00:00,  1.70it/s]
Requested to load IntegratedAutoencoderKL                                               memory_management.py :: INFO
Unloaded partially: 281.50 MB freed, 4615.56 MB remains loaded, 9.38 MB buffer reserved, lowvram     base.py :: INFO
patches: 0
loaded completely; 187.01 MB usable, 159.56 MB loaded, full load: True                               base.py :: INFO
Moving model(s) has taken 0.58 seconds                                                  memory_management.py :: INFO
Cleanup minimal inference memory...
tiled upscale (CPU Composite):   0%|                                                             | 0/6 [00:00<?, ?it/s]
Traceback (most recent call last):███████████████████▌                                | 50/100 [00:37<00:28,  1.73it/s]
  File "C:\Users\jairp\Programs\SD WebUI Forge Neo\modules_forge\main_thread.py", line 30, in work
    self.result = self.func(*self.args, **self.kwargs)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jairp\Programs\SD WebUI Forge Neo\modules\txt2img.py", line 135, in txt2img_function
    processed = processing.process_images(p)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jairp\Programs\SD WebUI Forge Neo\modules\processing.py", line 835, in process_images
    res = process_images_inner(p)
          ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jairp\Programs\SD WebUI Forge Neo\modules\processing.py", line 990, in process_images_inner
    samples_ddim = p.sample(conditioning=p.c, unconditional_conditioning=p.uc, seeds=p.seeds, subseeds=p.subseeds, subseed_strength=p.subseed_strength, prompts=p.prompts)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jairp\Programs\SD WebUI Forge Neo\modules\processing.py", line 1441, in sample
    return self.sample_hr_pass(samples, decoded_samples, seeds, subseeds, subseed_strength, prompts)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jairp\Programs\SD WebUI Forge Neo\modules\processing.py", line 1490, in sample_hr_pass
    image = images.resize_image(0, image, target_width, target_height, upscaler_name=self.hr_upscaler)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jairp\Programs\SD WebUI Forge Neo\modules\images.py", line 298, in resize_image
    res = resize(im, width, height)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jairp\Programs\SD WebUI Forge Neo\modules\images.py", line 290, in resize
    im = upscaler.scaler.upscale(im, scale, upscaler.data_path)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jairp\Programs\SD WebUI Forge Neo\modules\upscaler.py", line 56, in upscale
    img = self.do_upscale(img, selected_model)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jairp\Programs\SD WebUI Forge Neo\modules\esrgan_model.py", line 55, in do_upscale
    return upscale_with_model(
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jairp\Programs\SD WebUI Forge Neo\modules\upscaler_utils.py", line 279, in upscale_with_model
    return upscale_with_model_cpu(model, img, tile_size=tile_size, tile_overlap=tile_overlap, desc=f"{desc} (CPU Composite)")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jairp\Programs\SD WebUI Forge Neo\modules\upscaler_utils.py", line 250, in upscale_with_model_cpu
    output = upscale_pil_patch(model, tile)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jairp\Programs\SD WebUI Forge Neo\modules\upscaler_utils.py", line 219, in upscale_pil_patch
    return torch_bgr_to_pil_image(_model(model, tensor))
                                  ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jairp\Programs\SD WebUI Forge Neo\modules\upscaler_utils.py", line 73, in _model
    return model(x)
           ^^^^^^^^
  File "C:\Users\jairp\Programs\SD WebUI Forge Neo\venv\Lib\site-packages\torch\utils\_contextlib.py", line 120, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jairp\Programs\SD WebUI Forge Neo\venv\Lib\site-packages\spandrel\__helpers\model_descriptor.py", line 472, in __call__
    output = self._call_fn(self.model, image)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jairp\Programs\SD WebUI Forge Neo\venv\Lib\site-packages\spandrel\__helpers\model_descriptor.py", line 439, in <lambda>
    self._call_fn = call_fn or (lambda model, image: model(image))
                                                     ^^^^^^^^^^^^
  File "C:\Users\jairp\Programs\SD WebUI Forge Neo\venv\Lib\site-packages\torch\nn\modules\module.py", line 1775, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jairp\Programs\SD WebUI Forge Neo\venv\Lib\site-packages\torch\nn\modules\module.py", line 1786, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jairp\Programs\SD WebUI Forge Neo\venv\Lib\site-packages\spandrel\architectures\DRCT\__arch\drct_arch.py", line 857, in forward
    x = self.conv_after_body(self.forward_features(x)) + x
                             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jairp\Programs\SD WebUI Forge Neo\venv\Lib\site-packages\spandrel\architectures\DRCT\__arch\drct_arch.py", line 843, in forward_features
    x = layer(x, x_size)
        ^^^^^^^^^^^^^^^^
  File "C:\Users\jairp\Programs\SD WebUI Forge Neo\venv\Lib\site-packages\torch\nn\modules\module.py", line 1775, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jairp\Programs\SD WebUI Forge Neo\venv\Lib\site-packages\torch\nn\modules\module.py", line 1786, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jairp\Programs\SD WebUI Forge Neo\venv\Lib\site-packages\spandrel\architectures\DRCT\__arch\drct_arch.py", line 359, in forward
    self.pue(self.swin4(torch.cat((x, x1, x2, x3), -1), xsize), xsize)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jairp\Programs\SD WebUI Forge Neo\venv\Lib\site-packages\torch\nn\modules\module.py", line 1775, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jairp\Programs\SD WebUI Forge Neo\venv\Lib\site-packages\torch\nn\modules\module.py", line 1786, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jairp\Programs\SD WebUI Forge Neo\venv\Lib\site-packages\spandrel\architectures\DRCT\__arch\drct_arch.py", line 511, in forward
    attn_windows = self.attn(
                   ^^^^^^^^^^
  File "C:\Users\jairp\Programs\SD WebUI Forge Neo\venv\Lib\site-packages\torch\nn\modules\module.py", line 1775, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jairp\Programs\SD WebUI Forge Neo\venv\Lib\site-packages\torch\nn\modules\module.py", line 1786, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jairp\Programs\SD WebUI Forge Neo\venv\Lib\site-packages\spandrel\architectures\DRCT\__arch\drct_arch.py", line 201, in forward
    attn = attn + relative_position_bias.unsqueeze(0)
           ~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
torch.OutOfMemoryError: Allocation on device
Allocation on device

Total progress:  50%|████████████████████████████████▌                                | 50/100 [00:38<00:28,  1.73it/s]
```

**Comment by Haoming02** [comment]
Hello, this should be fixed~

**Comment by Speeskees** [comment]
Sorry for the late response. I've tested all my high VRAM usage workloads, and I haven't managed to reproduce the OOM in any way, it works great!
